### ISSUE TITLE
new amplifier module

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/HVAMP_32#1]
Some ion traps require a higher voltage than Fastino/Zotino can provide.
We already have an 8-channel HV amplifier but it is an overkill for ion traps,  in terms of power, cost, and channel density.
Let's take  32x LTC6090, pin-compatible DC/DC converters able to deliver various voltages and attach low noise HV LDO at the outputs. We need +/- 25V but let's make the design capable of up to +/- 70V.
The module will sit on top of the Fastino/Zotino using the same connectors as the Stabilizer mezzanine.
Alternatively, one can solder IDC connectors instead and connect them with a DAC card using IDC cables.
Any thoughts?

**Comment by gkasprow** [comment]
We will use the same connector as Zotino/Fastino so an upgrade of the existing setup would be quick and easy.

**Comment by dnadlinger** [comment]
Another possible option for future similar projects would be the new [OPA593](https://www.ti.com/lit/ds/symlink/opa593.pdf) – slightly lower noise, better offset/drift, but only up to ±42.5 V.

**Comment by gkasprow** [comment]
We will consider it for yet another QC project where +/-40V is needed. The PCBs were manufactured and initially tested. No issues so far.

**Comment by gkasprow** [comment]
We are making a lower noise version but also limited to roughly +/-45V
